### ISSUE TITLE
BIP-0044 Key Change Request

### ISSUE THREAD

**Issue by squirej** [slatecurrency/slate#20]
In order to complete the deployment of of the ledger nano integration, a replacement 
BIP-0044 Key must be selected and deployed to the Slate source code. A valid build of the source code must also be made available. 

- Selection of the BIP key.  Currently 0x800005fd is being targeted.
- Internals trace of the use of BIP Key
- Update the source code repositories 
- Compile replacement versions of for each target architecture
- Complete regression testing of the following actions: masternode stake, masternode rewards, transaction receive, transaction send, passive peer, txindex peer.

**Comment by squirej** [comment]
Decimal index 416 with hex code 0x800001a0 is what we have selected.

**Comment by slateapps** [comment]
Registered https://github.com/satoshilabs/slips/pull/578
